services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: bind9
    ports:
      - "53:53/tcp"
      - "53:53/udp"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - "80:80/tcp"