services:
  dns:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    ports:
      - "80:80/tcp"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - "81:80/tcp"